## PBLOCK — hardcoded RO banks (generated by scripts/gen_ro_presets.py)

create_pblock pblock_ro_bank10
resize_pblock [get_pblocks pblock_ro_bank10] -add {SLICE_X45Y45:SLICE_X55Y55}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank10]

create_pblock pblock_ro_bank0
resize_pblock [get_pblocks pblock_ro_bank0] -add {SLICE_X56Y45:SLICE_X59Y55}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank0]

create_pblock pblock_ro_bank3
resize_pblock [get_pblocks pblock_ro_bank3] -add {SLICE_X0Y45:SLICE_X12Y58}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank3]

create_pblock pblock_ro_bank1
resize_pblock [get_pblocks pblock_ro_bank1] -add {SLICE_X31Y46:SLICE_X37Y55}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank1]

create_pblock pblock_ro_bank2
resize_pblock [get_pblocks pblock_ro_bank2] -add {SLICE_X28Y45:SLICE_X30Y55}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank2]

create_pblock pblock_ro_bank4
resize_pblock [get_pblocks pblock_ro_bank4] -add {SLICE_X15Y16:SLICE_X24Y27}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank4]

create_pblock pblock_ro_bank7
resize_pblock [get_pblocks pblock_ro_bank7] -add {SLICE_X40Y16:SLICE_X49Y27}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank7]

create_pblock pblock_ro_bank8
resize_pblock [get_pblocks pblock_ro_bank8] -add {SLICE_X33Y16:SLICE_X39Y26}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank8]

create_pblock pblock_ro_bank5
resize_pblock [get_pblocks pblock_ro_bank5] -add {SLICE_X25Y31:SLICE_X32Y41}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank5]

create_pblock pblock_ro_bank9
resize_pblock [get_pblocks pblock_ro_bank9] -add {SLICE_X12Y30:SLICE_X19Y42}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank9]

create_pblock pblock_ro_bank11
resize_pblock [get_pblocks pblock_ro_bank11] -add {SLICE_X0Y30:SLICE_X11Y42}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank11]

create_pblock pblock_ro_bank6
resize_pblock [get_pblocks pblock_ro_bank6] -add {SLICE_X0Y0:SLICE_X10Y14}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank6]

create_pblock pblock_ro_bank12
resize_pblock [get_pblocks pblock_ro_bank12] -add {SLICE_X11Y0:SLICE_X21Y14}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank12]

create_pblock pblock_ro_bank13
resize_pblock [get_pblocks pblock_ro_bank13] -add {SLICE_X22Y0:SLICE_X32Y14}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank13]

create_pblock pblock_ro_bank14
resize_pblock [get_pblocks pblock_ro_bank14] -add {SLICE_X33Y0:SLICE_X43Y14}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank14]

create_pblock pblock_ro_bank15
resize_pblock [get_pblocks pblock_ro_bank15] -add {SLICE_X44Y0:SLICE_X54Y14}
set_property IS_SOFT FALSE [get_pblocks pblock_ro_bank15]
