#ifndef RO_TUNE_PRESETS_H
#define RO_TUNE_PRESETS_H
/* Auto-generated by scripts/gen_ro_presets.py */

#include "xil_types.h"

#define RO_PRESET_BANK_COUNT 16

typedef struct {
    u8  bank;
    u16 tune;
    u32 f_nom_hz;
} ro_tune_preset_t;

static const ro_tune_preset_t RO_TUNE_PRESETS[RO_PRESET_BANK_COUNT] = {
    { 10u, 0x000u, 120000000u },
    { 0u, 0x000u, 100000000u },
    { 3u, 0x060u, 55000000u },
    { 1u, 0x040u, 70000000u },
    { 2u, 0x080u, 62000000u },
    { 4u, 0x280u, 45000000u },
    { 7u, 0x300u, 30000000u },
    { 8u, 0x400u, 22000000u },
    { 5u, 0xC80u, 15000000u },
    { 9u, 0x900u, 10000000u },
    { 11u, 0xB00u, 5000000u },
    { 6u, 0x000u, 1000000u },
    { 12u, 0x000u, 800000u },
    { 13u, 0x000u, 600000u },
    { 14u, 0x000u, 400000u },
    { 15u, 0x000u, 300000u },
};

#endif
