// Auto-generated by scripts/gen_ro_presets.py
`timescale 1ns / 1ps

module ro_bank_tune_pack #(
    parameter int NUM_BANKS     = 16,
    parameter int NUM_TUNE_BITS = 12
) (
    output logic [NUM_BANKS * NUM_TUNE_BITS - 1:0] ro_tune_bus
);

  function automatic logic [NUM_TUNE_BITS-1:0] tune_for_bank(input logic [3:0] b);
    unique case (b)
      4'd10: tune_for_bank = 12'h000;
      4'd0: tune_for_bank = 12'h000;
      4'd3: tune_for_bank = 12'h060;
      4'd1: tune_for_bank = 12'h040;
      4'd2: tune_for_bank = 12'h080;
      4'd4: tune_for_bank = 12'h280;
      4'd7: tune_for_bank = 12'h300;
      4'd8: tune_for_bank = 12'h400;
      4'd5: tune_for_bank = 12'hC80;
      4'd9: tune_for_bank = 12'h900;
      4'd11: tune_for_bank = 12'hB00;
      4'd6: tune_for_bank = 12'h000;
      4'd12: tune_for_bank = 12'h000;
      4'd13: tune_for_bank = 12'h000;
      4'd14: tune_for_bank = 12'h000;
      4'd15: tune_for_bank = 12'h000;
      default: tune_for_bank = 12'hFFF;
    endcase
  endfunction

  generate
    genvar bi;
    for (bi = 0; bi < NUM_BANKS; bi++) begin : g_pack
      assign ro_tune_bus[(bi+1)*NUM_TUNE_BITS-1 : bi*NUM_TUNE_BITS] =
          tune_for_bank(4'(bi));
    end
  endgenerate

endmodule
