#!/usr/bin/env python3
"""Apply SDUP file header + 3-line English description to project RTL/SV sources."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SDUP_HEADER = """// =============================================================================
// Projekt SDUP — aring_osc
// A. Kowalczyk, K. Skalka
// Ring Oscillator Synthesizer — Arty S7-50 (V1 UART)
// =============================================================================
"""

# Three English sentences per file (basename).
DESCRIPTIONS: dict[str, list[str]] = {
    "ring_inverter_tunable.sv": [
        "Implements a tunable LUT-based ring oscillator for the high and mid-speed RO banks.",
        "The tune_sel bus selects longer or shorter inverter paths to change the loop delay and output frequency.",
        "Used inside ro_top for banks B1 through B11 in the V1 frequency synthesizer.",
    ],
    "ring_inverter_chain.sv": [
        "Implements a fixed-length chain of LUT inverters forming a slow ring oscillator.",
        "Provides stable low-frequency sources for banks B12 through B16 without software tuning.",
        "Instantiated in ro_top together with an optional output prescaler.",
    ],
    "ring_prog_toggle_div.sv": [
        "Programmable frequency divider that counts rising edges on the selected ring signal.",
        "Generates a divided square wave; minimum division is two when half_edges equals one.",
        "Sits on the output path so scope signals always pass through a divider in V1.",
    ],
    "ro_ring_prescale.sv": [
        "Asynchronous prescaler that divides a fast ring output before frequency measurement.",
        "Reduces edge rate seen by the 12 MHz counter to avoid aliasing on very fast rings.",
        "Used on slow chain banks and inside ro_bank_prescale_mux per bank class.",
    ],
    "ro_async_to_ref_sync.sv": [
        "Synchronizes an asynchronous ring oscillator signal into the system clock domain.",
        "Uses a multi-flop metastability buffer before edge counting or control logic.",
        "Feeds ro_freq_measure and related blocks that operate on clk at 12 MHz.",
    ],
    "ro_freq_hz_calc.sv": [
        "Computes output frequency in hertz from a gated edge count and reference clock.",
        "Implements f = edges * f_ref / (2 * gate_cycles) with optional scaling.",
        "Instantiated inside ro_freq_measure for hardware frequency readout.",
    ],
    "ro_freq_measure.sv": [
        "Gates and counts edges on a (possibly prescaled) ring or output signal.",
        "Runs entirely in the 12 MHz reference domain with programmable gate length.",
        "Exposes meas_busy, meas_done, edge count, and calculated frequency to the AXI CSR block.",
    ],
    "ro_top.sv": [
        "Core ring-oscillator bank array: sixteen generate blocks with tunable or chain rings.",
        "Selects one bank onto ro_out and optionally attaches local frequency measurement.",
        "Defines bank topology, tail lengths, and chain stage counts for the V1 synthesizer.",
    ],
    "csr_ro_axi_lite.sv": [
        "AXI4-Lite slave that maps MicroBlaze register accesses to RO control signals.",
        "Handles ro_en, bank select, tune word, divider, measurement arm, and status flags.",
        "Bridges the firmware in sw/v1_uart to the programmable logic of ro_top_arty_axi.",
    ],
    "ro_multi_div_mux.sv": [
        "Combines per-bank buffered ring outputs, target mapping, and the programmable divider.",
        "Selects the active bank and drives both scope output and measurement taps.",
        "Central output routing block between the sixteen rings and ro_sig_buf.",
    ],
    "ro_target_map.sv": [
        "Maps a target frequency in kilohertz to a ring bank and divider setting.",
        "Searches calibrated or nominal bank/d divider pairs to minimize frequency error.",
        "Used by ro_multi_div_mux when bank and divider are in automatic mode.",
    ],
    "ro_bank_prescale_mux.sv": [
        "Selects one of several async prescaler depths based on the active RO bank index.",
        "Outputs a scaled edge stream and a scale factor for firmware reconstruction.",
        "Feeds the ring-frequency measurement path in ro_top_arty_axi.",
    ],
    "ro_bank_tune_pack.sv": [
        "Read-only LUT that packs default 12-bit tune words for each hardware bank index.",
        "Values are generated by scripts/gen_ro_presets.py from characterization presets.",
        "Drives the initial tune bus in ro_top_arty_axi before firmware overrides TUNE.",
    ],
    "ro_ring_bank_buf.sv": [
        "Places a global clock buffer on each ring bank output before muxing.",
        "Isolates combinational RO loops from downstream load and routing delay.",
        "One instance per bank in ro_multi_div_mux.",
    ],
    "ro_sig_buf.sv": [
        "Buffers the final divided output with a BUFG for clean scope drive on JA.",
        "Sits after the programmable divider on the main synthesizer output path.",
        "Used in V1 instead of a clock-enabled buffer for continuous output viewing.",
    ],
    "ro_output_buffer.sv": [
        "Clock-enabled output buffer (BUFGCE) for gated RO or DDS paths.",
        "Legacy helper retained for the V2 button/DDS variant top level.",
        "Not used on the active V1 MicroBlaze UART code path.",
    ],
    "ro_bank_mux.sv": [
        "Simple multiplexer that selects one of several ring bank outputs.",
        "Legacy building block for early multi-bank tops and the V2 design.",
        "Superseded in V1 by ro_multi_div_mux but kept for archival builds.",
    ],
    "arty_scope_freq_mux.sv": [
        "High-speed observation mux that taps ring or output signals for oscilloscope pins.",
        "Uses MMCM multiplication to improve visibility of fast asynchronous waveforms on JA.",
        "Instantiated twice in ro_top_arty_axi for divided output and raw ring probes.",
    ],
    "btn_debouncer.sv": [
        "Debounces a mechanical button input and detects stable pressed and release edges.",
        "Runs synchronously in the board clock domain with programmable counter width.",
        "Used by the V2 DDS/button demonstrator, not by the V1 UART firmware flow.",
    ],
    "ro_top_arty_axi.sv": [
        "Top-level Arty S7 design for V1: MicroBlaze AXI CSR plus sixteen RO banks.",
        "Integrates measurement, divider mux, scope buffers, and SW0 ring enable gating.",
        "Wrapped as a module reference inside the Vivado block design mb_ro_system.",
    ],
    "ro_top_arty_axi_bd_wrap.v": [
        "Verilog wrapper that exposes ro_top_arty_axi ports for Vivado block-design automation.",
        "Renames the AXI slave interface to S_AXI for connection to microblaze_0_axi_periph.",
        "Required module reference (mref) entry for the custom RO IP in mb_ro_system.bd.",
    ],
    "ro_top_v2.sv": [
        "Alternate top level combining button inputs, DDS, and a buffered RO measurement path.",
        "Archived V2 laboratory variant; not built or programmed in the default V1 flow.",
        "Demonstrates debounced frequency change without MicroBlaze UART control.",
    ],
    "dds_core.sv": [
        "Direct digital synthesizer that produces a square wave from a phase accumulator MSB.",
        "Accepts a frequency tuning word and system clock for the V2 audio-style generator.",
        "Legacy module used only by ro_top_v2.",
    ],
    "dds_phase_accum.sv": [
        "32-bit phase accumulator for the V2 DDS signal generator.",
        "Adds the frequency tuning word each clock cycle and wraps on overflow.",
        "Feeds dds_core with the current phase state.",
    ],
    "freq_to_ftw.sv": [
        "Converts a requested output frequency in hertz to a DDS frequency tuning word.",
        "Uses fixed-point arithmetic with the configured system clock frequency.",
        "Supporting block for the V2 button-controlled DDS top.",
    ],
    "btn_freq_selector.sv": [
        "Interprets debounced up, down, and measure buttons into target frequency changes.",
        "Maintains the selected hertz value presented to the DDS and display logic.",
        "Part of the archived V2 DDS demonstration design.",
    ],
    "mb_ro_system_v2_wrapper.v": [
        "Block-design wrapper for the experimental V2 UART plus TFT system image.",
        "Archived netlist shell; the repository default programs V1 mb_ro_system_wrapper instead.",
        "Kept for reference when rebuilding the TFT branch locally.",
    ],
    "ro_top_v3.sv": [
        "Top-level that adds GC9A01 TFT display support alongside the RO measurement path.",
        "Archived V3 variant; display bring-up was not completed in the shipped V1 release.",
        "Combines SPI display driver hooks with ring frequency status outputs.",
    ],
    "ro_top_v3_wrapper.v": [
        "Verilog wrapper for ro_top_v3 used in Vivado block-design integration.",
        "Exposes display and RO ports to the V3 experimental bitstream top.",
        "Not used when building the default V1 UART bitstream.",
    ],
    "gc9a01_driver.sv": [
        "Controller for the GC9A01 round TFT display over SPI (240x240).",
        "Handles reset, initialization sequence, and drawing measured frequency text.",
        "Part of the archived V3 TFT branch only.",
    ],
    "spi_master.sv": [
        "SPI mode-0 master with programmable clock division for display and peripheral IO.",
        "Shifts one byte per transaction and handshakes with busy/done status.",
        "Used by gc9a01_driver in the V3 TFT experimental design.",
    ],
    "tb_v1_meas_flow.sv": [
        "Self-checking testbench for V1 ring measurement and divider behavior.",
        "Stimulates bank select, tune, and measurement arm sequences in simulation.",
        "Verifies edge counting and frequency reconstruction against expected ranges.",
    ],
    "tb_btn_debouncer.sv": [
        "Unit testbench for the btn_debouncer module with synthetic bounce waveforms.",
        "Checks that only stable presses produce a single detected edge.",
        "Supports regression of the V2 input path in XSim.",
    ],
    "tb_dds_core.sv": [
        "Simulation testbench for the DDS phase accumulator and square-wave output.",
        "Applies several tuning words and observes output period on the waveform.",
        "Used to validate the archived V2 generator before FPGA implementation.",
    ],
    "tb_spi_master.sv": [
        "Testbench that sends byte streams through spi_master and monitors SCK/MOSI.",
        "Confirms CPOL/CPHA timing and transaction completion signaling.",
        "Supports bring-up of the V3 display SPI interface in simulation.",
    ],
    "tb_ro_top.sv": [
        "Generic behavioral testbench for legacy ro_top connectivity and measurement.",
        "Exercises ring enable, bank mux, and basic frequency gate completion.",
        "Retained for gate-level and RTL regression in the Vivado sim_1 fileset.",
    ],
    "tb_ro_tune_sweep.sv": [
        "Sweep testbench that steps tune_sel across the full range for one RO bank.",
        "Records edge counts or frequency estimates to characterize tuning monotonicity.",
        "Used offline to refine presets in gen_ro_presets.py.",
    ],
}

HEADER_END = "// =============================================================================\n"
AUTO_GEN = "// Auto-generated by scripts/gen_ro_presets.py"


def should_process(p: Path) -> bool:
    if p.suffix not in {".sv", ".v"}:
        return False
    parts = p.parts
    if "ring_oscilator_prj.srcs" in parts:
        rel = p.relative_to(ROOT / "ring_oscilator_prj.srcs")
        if rel.parts[0] == "sources_1" and "new" in rel.parts:
            return True
        if rel.parts[0] == "sim_1":
            return True
        return False
    return "rtl" in parts or "sim" in parts


def format_description(lines: list[str]) -> str:
    return "".join(f"// {s}\n" for s in lines) + "\n"


def build_preamble(name: str) -> str:
    desc = DESCRIPTIONS.get(name)
    if not desc:
        raise KeyError(f"No description for {name}")
    body = SDUP_HEADER + "\n"
    if name == "ro_bank_tune_pack.sv":
        body += AUTO_GEN + "\n"
    body += format_description(desc)
    return body


def strip_old_preamble(text: str) -> str:
    """Remove SDUP header and following comment lines until timescale/module."""
    if "Projekt SDUP" not in text:
        return text
    m = re.search(r"^(`timescale|module\s)", text, re.MULTILINE)
    if not m:
        return text
    return text[m.start() :]


def process_file(path: Path) -> None:
    name = path.name
    if name not in DESCRIPTIONS:
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    rest = strip_old_preamble(text).lstrip("\n")
    new_text = build_preamble(name) + rest
    if not new_text.endswith("\n"):
        new_text += "\n"
    path.write_text(new_text, encoding="utf-8", newline="\n")


def main() -> int:
    n = 0
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and should_process(p):
            if p.name in DESCRIPTIONS:
                process_file(p)
                n += 1
                print("OK", p.relative_to(ROOT))
    print(f"Updated {n} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
