#!/usr/bin/env python3
"""Emit hardcoded RO bank tune presets + PBLOCK regions from characterization targets."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SDUP_SV_HEADER = """// =============================================================================
// Projekt SDUP — aring_osc
// A. Kowalczyk, K. Skalka
// Ring Oscillator Synthesizer — Arty S7-50 (V1 UART)
// =============================================================================

"""

# bank HW id, tune12, nominal Hz, PBLOCK slice rect (xc7s50) — no overlap
PRESETS = [
    {"bank": 10, "tune": 0x000, "f_hz": 120_000_000, "rect": "SLICE_X45Y45:SLICE_X55Y55"},
    {"bank": 0,  "tune": 0x000, "f_hz": 100_000_000, "rect": "SLICE_X56Y45:SLICE_X59Y55"},
    {"bank": 3,  "tune": 0x060, "f_hz": 55_000_000,  "rect": "SLICE_X0Y45:SLICE_X12Y58"},
    {"bank": 1,  "tune": 0x040, "f_hz": 70_000_000,  "rect": "SLICE_X31Y46:SLICE_X37Y55"},
    {"bank": 2,  "tune": 0x080, "f_hz": 62_000_000,  "rect": "SLICE_X28Y45:SLICE_X30Y55"},
    {"bank": 4,  "tune": 0x280, "f_hz": 45_000_000,  "rect": "SLICE_X15Y16:SLICE_X24Y27"},
    {"bank": 7,  "tune": 0x300, "f_hz": 30_000_000,  "rect": "SLICE_X40Y16:SLICE_X49Y27"},
    {"bank": 8,  "tune": 0x400, "f_hz": 22_000_000,  "rect": "SLICE_X33Y16:SLICE_X39Y26"},
    {"bank": 5,  "tune": 0xC80, "f_hz": 15_000_000,  "rect": "SLICE_X25Y31:SLICE_X32Y41"},
    {"bank": 9,  "tune": 0x900, "f_hz": 10_000_000,  "rect": "SLICE_X12Y30:SLICE_X19Y42"},
    {"bank": 11, "tune": 0xB00, "f_hz": 5_000_000,   "rect": "SLICE_X0Y30:SLICE_X11Y42"},
    {"bank": 6,  "tune": 0x000, "f_hz": 1_000_000,   "rect": "SLICE_X0Y0:SLICE_X10Y14"},
    {"bank": 12, "tune": 0x000, "f_hz": 800_000,    "rect": "SLICE_X11Y0:SLICE_X21Y14"},
    {"bank": 13, "tune": 0x000, "f_hz": 600_000,    "rect": "SLICE_X22Y0:SLICE_X32Y14"},
    {"bank": 14, "tune": 0x000, "f_hz": 400_000,    "rect": "SLICE_X33Y0:SLICE_X43Y14"},
    {"bank": 15, "tune": 0x000, "f_hz": 300_000,    "rect": "SLICE_X44Y0:SLICE_X54Y14"},
]


def write_tune_header(path: Path) -> None:
    lines = [
        "#ifndef RO_TUNE_PRESETS_H",
        "#define RO_TUNE_PRESETS_H",
        "/* Auto-generated by scripts/gen_ro_presets.py */",
        "",
        "#include \"xil_types.h\"",
        "",
        f"#define RO_PRESET_BANK_COUNT {len(PRESETS)}",
        "",
        "typedef struct {",
        "    u8  bank;",
        "    u16 tune;",
        "    u32 f_nom_hz;",
        "} ro_tune_preset_t;",
        "",
        "static const ro_tune_preset_t RO_TUNE_PRESETS[RO_PRESET_BANK_COUNT] = {",
    ]
    for p in PRESETS:
        lines.append(
            f"    {{ {p['bank']}u, 0x{p['tune']:03X}u, {p['f_hz']}u }},"
        )
    lines += [
        "};",
        "",
        "#endif",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", path)


def write_floorplan_xdc(path: Path) -> None:
    lines = [
        "## PBLOCK — hardcoded RO banks (generated by scripts/gen_ro_presets.py)",
        "",
    ]
    for p in PRESETS:
        b = p["bank"]
        rect = p["rect"]
        pb = f"pblock_ro_bank{b}"
        lines += [
            f"create_pblock {pb}",
            f"resize_pblock [get_pblocks {pb}] -add {{{rect}}}",
            f"set_property IS_SOFT FALSE [get_pblocks {pb}]",
            "",
        ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", path)


def write_sv_tune_pack(path: Path) -> None:
    tune_desc = [
        "// Read-only LUT that packs default 12-bit tune words for each hardware bank index.",
        "// Values are generated by scripts/gen_ro_presets.py from characterization presets.",
        "// Drives the initial tune bus in ro_top_arty_axi before firmware overrides TUNE.",
    ]
    lines = [
        SDUP_SV_HEADER.rstrip("\n"),
        "// Auto-generated by scripts/gen_ro_presets.py",
        *tune_desc,
        "",
        "`timescale 1ns / 1ps",
        "",
        "module ro_bank_tune_pack #(",
        "    parameter int NUM_BANKS     = 16,",
        "    parameter int NUM_TUNE_BITS = 12",
        ") (",
        "    output logic [NUM_BANKS * NUM_TUNE_BITS - 1:0] ro_tune_bus",
        ");",
        "",
        "  function automatic logic [NUM_TUNE_BITS-1:0] tune_for_bank(input logic [3:0] b);",
        "    unique case (b)",
    ]
    for p in PRESETS:
        lines.append(f"      4'd{p['bank']:1d}: tune_for_bank = 12'h{p['tune']:03X};")
    lines += [
        "      default: tune_for_bank = 12'hFFF;",
        "    endcase",
        "  endfunction",
        "",
        "  generate",
        "    genvar bi;",
        "    for (bi = 0; bi < NUM_BANKS; bi++) begin : g_pack",
        "      assign ro_tune_bus[(bi+1)*NUM_TUNE_BITS-1 : bi*NUM_TUNE_BITS] =",
        "          tune_for_bank(4'(bi));",
        "    end",
        "  endgenerate",
        "",
        "endmodule",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", path)


def main() -> int:
    write_tune_header(ROOT / "sw" / "v1_uart" / "ro_tune_presets.h")
    write_floorplan_xdc(ROOT / "constraints" / "v1_uart" / "floorplan_ro_banks.xdc")
    write_sv_tune_pack(ROOT / "rtl" / "common" / "ro_bank_tune_pack.sv")
    sdk = ROOT / "sdk_workspace" / "ro_ring_app" / "src" / "ro_tune_presets.h"
    write_tune_header(sdk)
    src_new = ROOT / "ring_oscilator_prj.srcs" / "sources_1" / "new" / "ro_bank_tune_pack.sv"
    write_sv_tune_pack(src_new)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
