# Post-implementation: extract LUT/SLICE site names per RO bank -> sw/v1_uart/lut_mapping.h
# Usage: vivado -mode batch -source scripts/gen_lut_mapping.tcl

set proj_dir [file normalize [file dirname [info script]]/..]
cd $proj_dir

if {[catch {current_project} _]} {
  if {[file exists ring_oscilator_prj.xpr]} {
    open_project ring_oscilator_prj.xpr
  }
}
if {[get_runs impl_1 -quiet] ne "" && [catch {current_design} _]} {
  open_run impl_1
}

set out_h "$proj_dir/sw/v1_uart/lut_mapping.h"
set fp [open $out_h w]

puts $fp "#ifndef LUT_MAPPING_H"
puts $fp "#define LUT_MAPPING_H"
puts $fp "/* Auto-generated by scripts/gen_lut_mapping.tcl */"
puts $fp ""
puts $fp "#define RO_LUT_BANK_COUNT 4"
puts $fp ""
puts $fp "static const char *const RO_LUT_BANK_NAMES\[RO_LUT_BANK_COUNT\] = {"
puts $fp "    \"BANK10\", \"BANK3\", \"BANK4\", \"BANK5\""
puts $fp "};"
puts $fp ""
puts $fp "static const u8 RO_LUT_BANK_HW_ID\[RO_LUT_BANK_COUNT\] = { 10, 3, 4, 5 };"
puts $fp ""

set bank_list {10 3 4 5}
set idx 0

foreach b $bank_list {
  set pat [format {*g_bank[%s]*} $b]
  set lut_cells [get_cells -hierarchical -quiet -filter "NAME =~ $pat && PRIMITIVE_TYPE =~ *LUT*"]
  if {[llength $lut_cells] == 0} {
    set lut_cells [get_cells -hierarchical -quiet -filter "NAME =~ $pat"]
  }

  puts $fp "static const char *const RO_LUT_BANK$b\[\] = {"
  set n 0
  foreach c $lut_cells {
    set site [get_property SITE $c]
    if {$site eq ""} { set site [get_property NAME $c] }
    puts $fp "    \"$site\","
    incr n
    if {$n >= 32} { break }
  }
  if {$n == 0} {
    puts $fp "    \"(no routed cells — run impl first)\","
  }
  puts $fp "    NULL"
  puts $fp "};"
  puts $fp ""
  incr idx
}

puts $fp "static const char *const *const RO_LUT_BANK_CELLS\[RO_LUT_BANK_COUNT\] = {"
puts $fp "    RO_LUT_BANK10, RO_LUT_BANK3, RO_LUT_BANK4, RO_LUT_BANK5"
puts $fp "};"
puts $fp ""
puts $fp "#endif"
close $fp

puts "Wrote $out_h"
